services:
  takaro-operator:
    build:
      context: .
      dockerfile: Dockerfile
    image: takaro-operator:dev
    container_name: takaro-operator
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - HEALTH_PORT=15080
      - METRICS_PORT=15090
      - KUBERNETES_NAMESPACE=takaro-system
      - WATCH_NAMESPACES=default,takaro-test
      # Mount kubeconfig for local development
      - KUBECONFIG=/home/node/.kube/config
    ports:
      - "15080:15080"  # Health endpoints
      - "15090:15090"  # Metrics endpoint
    volumes:
      # Mount kubeconfig from host for local development
      - ${HOME}/.kube:/home/node/.kube:ro
    restart: unless-stopped
    networks:
      - takaro-network

networks:
  takaro-network:
    driver: bridge