apiVersion: takaro.io/v1
kind: Domain
metadata:
  name: test-domain-adopt
  namespace: takaro-system
spec:
  name: "test-domain"
  externalReference: "k8s-operator-takaro-system-test-domain-c16b58c0"  # Existing domain to adopt
  limits:
    maxGameServers: 5
    maxUsers: 50
  settings:
    maintenanceMode: false