apiVersion: takaro.io/v1
kind: Domain
metadata:
  name: production-domain
  namespace: takaro-system
  labels:
    environment: production
    team: gameops
spec:
  name: production-game-servers
  gameServerId: "game-server-123"
  limits:
    maxPlayers: 1000
    maxGameServers: 20
    maxUsers: 500
  settings:
    maintenanceMode: false
    publiclyVisible: true
    allowRegistration: true
  takaroConfig:
    features:
    - advanced-analytics
    - custom-commands
    - economy-system