apiVersion: takaro.io/v1
kind: Domain
metadata:
  name: maintenance-domain
  namespace: takaro-system
spec:
  name: staging-servers
  limits:
    maxPlayers: 50
    maxGameServers: 5
    maxUsers: 100
  settings:
    maintenanceMode: true
    publiclyVisible: false
    allowRegistration: false