apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domains.takaro.io
spec:
  group: takaro.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - name
            - externalReference
            properties:
              name:
                type: string
                description: The name of the domain to create in Takaro
              externalReference:
                type: string
                description: External reference ID for the domain in Takaro
              gameServerId:
                type: string
                description: Optional game server ID to associate with the domain
              limits:
                type: object
                properties:
                  maxPlayers:
                    type: integer
                    minimum: 1
                    maximum: 10000
                  maxGameServers:
                    type: integer
                    minimum: 1
                    maximum: 100
                  maxUsers:
                    type: integer
                    minimum: 1
                    maximum: 10000
              settings:
                type: object
                properties:
                  maintenanceMode:
                    type: boolean
                    default: false
                  publiclyVisible:
                    type: boolean
                    default: true
                  allowRegistration:
                    type: boolean
                    default: true
              takaroConfig:
                type: object
                properties:
                  apiUrl:
                    type: string
                  features:
                    type: array
                    items:
                      type: string
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                - Pending
                - Creating
                - Ready
                - Error
                - Deleting
              externalReferenceId:
                type: string
              registrationToken:
                type: string
              rootUserCredentials:
                type: object
                properties:
                  username:
                    type: string
                  secretName:
                    type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                      - Ready
                      - Synced
                      - Error
                    status:
                      type: string
                      enum:
                      - "True"
                      - "False"
                      - "Unknown"
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
              lastReconcileTime:
                type: string
              observedGeneration:
                type: integer
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Domain Name
      type: string
      jsonPath: .spec.name
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: External ID
      type: string
      jsonPath: .status.externalReferenceId
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: domains
    singular: domain
    kind: Domain
    shortNames:
    - dom