apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domains.takaro.io
spec:
  group: takaro.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              externalReference:
                type: string
              gameServerId:
                type: string
              limits:
                type: object
              settings:
                type: object
              takaroConfig:
                type: object
          status:
            type: object
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Domain Name
      type: string
      jsonPath: .spec.name
      description: The name of the domain in Takaro
    - name: Phase
      type: string
      jsonPath: .status.phase
      description: Current phase of the domain
    - name: External ID
      type: string
      jsonPath: .status.externalReferenceId
      description: External reference ID in Takaro
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
      description: Age of the resource
  scope: Namespaced
  names:
    plural: domains
    singular: domain
    kind: Domain
    shortNames:
    - dom